kind: source
spec:
  name: aws
  path: cloudquery/aws
  version: "v15.6.0"
  tables: ["*"]
  destinations: ["postgresql"] 
  spec:
    regions:
      - us-west-1
      - us-east-1
    accounts:
      - id: "orgs"
        local_profile: "orgs"
    aws_debug: true

---
kind: destination
spec:
  name: postgresql
  path: cloudquery/postgresql
  version: "v3.0.2"
  spec:
    connection_string: "postgresql://postgres:pass@localhost:5432/postgres?sslmode=disable"
